language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t local-react -f Dockerfile.dev .

script:
  - docker run -e CI=true local-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'workflow-app'
  env: 'Workflowapp-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-329048240760'
  bucket_path: 'workflow-app'
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"