language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t local-react -f Dockerfile.dev .

script:
  - docker run -e CI=true local-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'weather-app'
  env: 'Weatherapp-env'
  bucket_name: 'elasticbeanstalk-us-west-1-329048240760'
  bucket_path: 'weather-app'
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"